name: "Herman Lab"
description: "This is the official web page for the Mark A. Herman Lab at Duke University."

url: "https://markhermanlab.org/"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown: 
  parse_block_html: true
